version: '3'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file: ./frontend/.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
